apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: element-ingressroute-certificate
  namespace: cert-manager
spec:
  # Secret names are always required.
  secretName: element-ingressroute-certificate

  issuerRef:
    name: digitalocean-clusterissuer
    kind: ClusterIssuer

  dnsNames:
    - tym.myr-project.eu

  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "element"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "element"
