apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kanidm-ingressroute-certificate
  namespace: kanidm
spec:
  # Secret names are always required.
  secretName: kanidm-ingressroute-certificate

  issuerRef:
    name: digitalocean-clusterissuer
    kind: ClusterIssuer

  dnsNames:
    - auth.myr-project.eu

  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "kanidm"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "kanidm"
