---
# Source: vaultwarden/charts/vaultwarden/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vaultwarden-svc
  namespace: vaultwarden
  labels:
    app.kubernetes.io/component: vaultwarden
    helm.sh/chart: vaultwarden-0.31.6
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/instance: cnpg
    app.kubernetes.io/version: "1.33.2"
    app.kubernetes.io/managed-by: Helm
---
# Source: vaultwarden/charts/vaultwarden/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-vaultwarden
  namespace: vaultwarden
  labels:
    app.kubernetes.io/component: vaultwarden
    helm.sh/chart: vaultwarden-0.31.6
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/instance: cnpg
    app.kubernetes.io/version: "1.33.2"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  YUBICO_SECRET_KEY: ""
  DUO_SKEY: ""
  SMTP_PASSWORD: ""
  SMTP_USERNAME: ""
  PUSH_INSTALLATION_ID: ""
  PUSH_INSTALLATION_KEY: ""
  ADMIN_TOKEN: "JGFyZ29uMmlkJHY9MTkkbT0xOTQ1Nix0PTIscD0xJFZreDFWa0U0Um1oRE1VaHdObTlZVmxoUFFrVk9aazFZYzFkdVNEZEdSVll6ZDBZNVprZ3dhVmcwWXowJFBLK2gxQU5DYnp6bUVLYWlRZkNqV3craFdGYU1LdkxoRzJQalJhbkg1S2s="
---
# Source: vaultwarden/charts/vaultwarden/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cnpg-vaultwarden
  namespace: vaultwarden
  labels:
    app.kubernetes.io/component: vaultwarden
    helm.sh/chart: vaultwarden-0.31.6
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/instance: cnpg
    app.kubernetes.io/version: "1.33.2"
    app.kubernetes.io/managed-by: Helm
data:
  DOMAIN: "https://pass.myr-project.eu"
  ROCKET_ADDRESS: "0.0.0.0"
  ROCKET_PORT: "8080"
  ROCKET_WORKERS: "10"
  SHOW_PASSWORD_HINT: "false"
  SIGNUPS_ALLOWED: "true"
  INVITATIONS_ALLOWED: "true"
  SIGNUPS_VERIFY: "true"
  WEB_VAULT_ENABLED: "true"
  DB_CONNECTION_RETRIES: "15"
  DATABASE_MAX_CONNS: "10"
  INVITATION_ORG_NAME: "Vaultwarden"
  ICON_BLACKLIST_NON_GLOBAL_IPS: "true"
  IP_HEADER: "X-Real-IP"
  ORG_EVENTS_ENABLED: "false"
  ORG_GROUPS_ENABLED: "false"
  SENDS_ALLOWED: "true"
  EMERGENCY_ACCESS_ALLOWED: "true"
  EMERGENCY_NOTIFICATION_REMINDER_SCHEDULE: "0 3 * * * *"
  EMERGENCY_REQUEST_TIMEOUT_SCHEDULE: "0 7 * * * *"
  EXTENDED_LOGGING: "true"
  LOG_TIMESTAMP_FORMAT: "%Y-%m-%d %H:%M:%S.%3f"
  ICON_SERVICE: "internal"
  ICON_REDIRECT_CODE: "302"
  INVITATION_EXPIRATION_HOURS: "120"
  REQUIRE_DEVICE_EMAIL: "false"
  TRASH_AUTO_DELETE_DAYS: ""
  EMAIL_CHANGE_ALLOWED: "true"
  ADMIN_RATELIMIT_SECONDS: "300"
  ADMIN_RATELIMIT_MAX_BURST: "3"
---
# Source: vaultwarden/charts/vaultwarden/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cnpg-vaultwarden
  namespace: vaultwarden
  labels:
    app.kubernetes.io/component: vaultwarden
    helm.sh/chart: vaultwarden-0.31.6
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/instance: cnpg
    app.kubernetes.io/version: "1.33.2"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
# Source: vaultwarden/charts/vaultwarden/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cnpg-vaultwarden
  namespace: vaultwarden
  labels:
    app.kubernetes.io/component: vaultwarden
    helm.sh/chart: vaultwarden-0.31.6
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/instance: cnpg
    app.kubernetes.io/version: "1.33.2"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cnpg-vaultwarden
subjects:
  - kind: ServiceAccount
    name: vaultwarden-svc
---
# Source: vaultwarden/charts/vaultwarden/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cnpg-vaultwarden
  namespace: vaultwarden
  labels:
    app.kubernetes.io/component: vaultwarden
    helm.sh/chart: vaultwarden-0.31.6
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/instance: cnpg
    app.kubernetes.io/version: "1.33.2"
    app.kubernetes.io/managed-by: Helm
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/component: vaultwarden
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/instance: cnpg
  ports:
    - name: "http"
      port: 80
      protocol: TCP
      targetPort: 8080
  ipFamilyPolicy: SingleStack
---
# Source: vaultwarden/charts/vaultwarden/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cnpg-vaultwarden
  namespace: vaultwarden
  labels:
    app.kubernetes.io/component: vaultwarden
    helm.sh/chart: vaultwarden-0.31.6
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/instance: cnpg
    app.kubernetes.io/version: "1.33.2"
    app.kubernetes.io/managed-by: Helm
spec:
  serviceName: vaultwarden
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: vaultwarden
      app.kubernetes.io/name: vaultwarden
      app.kubernetes.io/instance: cnpg
  template:
    metadata:
      labels:
        app.kubernetes.io/component: vaultwarden
        app.kubernetes.io/name: vaultwarden
        app.kubernetes.io/instance: cnpg
      annotations:
        checksum/config: cb3be9177e102d7aec2049ba0f1a3999ddb0840d
        checksum/secret: 2e59b80e86cef29e47b2e9ebddcb64daa9ed0cac
    spec:
      containers:
        - image: docker.io/vaultwarden/server:1.33.2-alpine
          imagePullPolicy: IfNotPresent
          name: vaultwarden
          envFrom:
            - configMapRef:
                name: cnpg-vaultwarden
          env:
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cnpg-vaultwarden
                  key: ADMIN_TOKEN
            - name: DATABASE_URL
              value: postgresql://app:password@cluster-rw.database.svc.cluster.local:5432/vwdb
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources: {}
          livenessProbe:
            httpGet:
              path: /alive
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /alive
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
      serviceAccountName: vaultwarden-svc
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
---
# Source: vaultwarden/charts/vaultwarden/templates/ingress.yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cnpg-vaultwarden
  namespace: vaultwarden
  labels:
    app.kubernetes.io/component: vaultwarden
    helm.sh/chart: vaultwarden-0.31.6
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/instance: cnpg
    app.kubernetes.io/version: "1.33.2"
    app.kubernetes.io/managed-by: Helm
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pass.myr-project.eu`)
      kind: Rule
      services:
        - name: cnpg-vaultwarden
          port: 80
      middlewares:
        - name: redirect-https
  tls:
    secretName: <your-tls-secret-name>
