apiVersion: v1
kind: Secret
metadata:
  name: wireguard
  namespace: vpn
type: Opaque
stringData:
  wg0.conf.template: |
    [Interface]
    Address = 172.16.16.1/20
    ListenPort = 51820
    PrivateKey = 4Fp/vx4xjTAIcykuU8TWUslECk4ponmS7z0Zmn+79GI=
    PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    PostUp = sysctl -w -q net.ipv4.ip_forward=1
    PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
    PostDown = sysctl -w -q net.ipv4.ip_forward=0

    [Peer]
    PublicKey = WykRW+rBpeclQBxQmgmLV9JUfK77GNGvrC8fIdCuqGs=
    AllowedIPs = 127.16.16.2/32
    PersistentKeepalive = 25
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  namespace: vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      initContainers:
      - name: wireguard-template-replacement
        image: busybox
        command:
        - sh
        - "-c"
        - |
          ENI=$(ip route get 1.1.1.1 | grep 1.1.1.1 | awk '{print $5}')
          sed "s/ENI/$ENI/g" /etc/wireguard-secret/wg0.conf.template > /config/wg_confs/wg0.conf
          chmod 400 /config/wg_confs/wg0.conf
        volumeMounts:
        - mountPath: "/config/wg_confs/"
          name: wireguard-config
        - mountPath: "/etc/wireguard-secret/"
          name: wireguard-secret
      containers:
      - name: wireguard
        image: linuxserver/wireguard:latest
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
          privileged: true  # Permet d'exécuter sysctl et iptables
        ports:
        - containerPort: 51820
        env:
        - name: PEERS
          value: ""
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: ALLOWEDIPS
          value: 0.0.0.0/0
        - name: SERVERPORT
          value: '31501'
        - name: SERVERURL
          value: vpn.myr-project.eu
        volumeMounts:
        - mountPath: "/config/wg_confs/"
          name: wireguard-config
      volumes:
      - name: wireguard-config
        emptyDir: {}
      - name: wireguard-secret
        secret:
          secretName: wireguard
---
apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: vpn
spec:
  ports:
    - name: wireguard
      port: 51820
      protocol: UDP
      targetPort: 51820
  selector:
    app: wireguard
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: wireguard
  namespace: vpn
spec:
  entryPoints:
    - udp
  routes:
    - services:
        - name: wireguard
          port: 51820