apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: matrix-ingressroute-certificate
  namespace: cert-manager
spec:
  # Secret names are always required.
  secretName: matrix-ingressroute-certificate

  issuerRef:
    name: digitalocean-clusterissuer
    kind: ClusterIssuer

  dnsNames:
    - matrix.myr-project.eu

  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "matrix"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "matrix"
