kind: Cluster
name: omni-contrib
talos:
  version: v1.7.4
kubernetes:
  version: 1.30.1
features:
  enableWorkloadProxy: true
patches:
  - name: cni
    file: patches/cni.yaml
---
kind: ControlPlane
machineClass:
  name: omni-contrib-controlplane
  size: 2
patches:
  - name: cilium
    file: patches/cilium.yaml
  # - name: argocd
  #   file: patches/argocd.yaml
  - name: monitoring
    file: patches/monitoring.yaml
  - name: traefik
    file: patches/traefik.yaml
---
kind: Workers
name: workers
machineClass:
  name: omni-contrib-workers
  size: unlimited
