apiVersion: v1
data:
  username: YXBw  # base64 encoded "app"
  password: cGFzc3dvcmQ=  # base64 encoded "password"
kind: Secret
metadata:
  name: app-db-password
  namespace: database
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster
  namespace: database
spec:
  instances: 1

  storage:
    size: 1Gi

  managed:
    roles:
      - name: app
        ensure: present
        passwordSecret:
          name: app-db-password
    services:
      disabledDefaultServices: ["r"]
