apiVersion: v1
data:
  username: YXBw # base64 encoded "app"
  password: cGFzc3dvcmQ= # base64 encoded "password"
kind: Secret
metadata:
  name: app-db-password
  namespace: database
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
---
# https://github.com/cloudnative-pg/charts/blob/main/charts/cluster/values.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster
  namespace: database
spec:
  instances: 1

  storage:
    storageClass: "local-path"
    size: 1Gi

  postgresql:
    pg_hba:
      - host all all all md5

  managed:
    roles:
      - name: app
        ensure: present
        passwordSecret:
          name: app-db-password
        login: true
    services:
      disabledDefaultServices: ["r"]
