apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce  # Only one node can mount it at a time
  persistentVolumeReclaimPolicy: Retain  # Keeps data after PVC is deleted
  storageClassName: manual
  hostPath:
    path: "/mnt/data"  # Directory on the node
