traefik:
  ingressRoute:
    dashboard:
      enabled: true
      entryPoints: ["web", "websecure"]
      matchRule: Host(`traefik.myr-project.eu`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      services:
        - name: api@internal
          kind: TraefikService
      tls :
        secretName: traefik-ingressroute-certificate
  service:
    enabled: true
    hostNetwork: true
    type: LoadBalancer  # Use LoadBalancer for external access
    externalIPs:
    - 34.175.175.3
    - 34.175.155.111
  ports:
    web:
      port: 31500        # HTTP port
      default : true
      nodePort: 31500
    websecure:
      port: 31501       # HTTPS port
      default : true
      nodePort: 31501
    udp:
      port: 51820
      protocol: UDP
      default: true
