---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: digitalocean-clusterissuer
spec:
  acme:
    email: asphalt8fr@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: digitalocean-clusterissuer-account-key
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-dns
              key: access-token
