---
apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-dns
  namespace: cert-manager
data:
  access-token: "ZG9wX3YxXzIwOGI1NjRiZDE0Y2FmMjMzZTQ4ZDkwNGE3N2IyYTM0ODQ0ZDlmNjM5NjA2Mzg4NzcwYzdmOWQ2ZTc5Y2YzYjY="
